name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: install deps
        run: npm install

# add tests and linting later